replicaCount: 1

image:
  repository: rodrigordavila/players
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  linkerd.io/inject: enabled
  ingress.kubernetes.io/service-upstream: "true"
  nginx.ingress.kubernetes.io/service-upstream: "true"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9999

kong:
  enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/preserve-host: "false"
    konghq.com/strip-path: "true"
    konghq.com/plugins: prometheus-matches,matches-otel
  hosts:
    - host: ""
      paths:
        - path: /api/players
          pathType: Prefix
          port: 9999
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 10Mi
  requests:
    cpu: 100m
    memory: 5Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

podLabels:
  app: players
